name: 'S3 and CloudFront Deploy'
description: 'Deploy a static website to AWS S3 and invalidate CloudFront distribution path(s)'
inputs:
  folder:
    description: 'build'
    required: true
  bucket: 
    description: ${{ secrets.S3_BUCKET }}
    required: true
  dist-id:
    description: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    required: true
  invalidation:
    description: '/'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'
