- name: S3 and CloudFront Deploy
  uses: lbertenasco/s3-deploy@v1.2.4
with:
    folder: build
    bucket: ${{ secrets.S3_BUCKET }}
    dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    invalidation: / *
